# Generated by Django 4.2.7 on 2023-11-16 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contractorControl", "0002_timeclock_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeclock",
            name="time",
            field=models.TimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
